steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy infrrastructure
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud deployment-manager deployments create mi-despliegue --config config.yaml 

options:
  logging: CLOUD_LOGGING_ONLY